### ISSUE TITLE
Problems (which seems self-solved already)

### ISSUE THREAD

**Issue by yuewumay** [yuewumay/hello-world#4]
1. Quotes：即便将图1的代码复制粘贴过来，出来的效果也不是图2；最后我是让“-”紧随其后而非另起一行实现的。
![Quotes1](https://github.com/yuewumay/hello-world/blob/master/Quotes1.png)
![Quotes2](https://github.com/yuewumay/hello-world/blob/master/Quotes2.png)
2. 如何将Git Bash与类似vim的其它编辑器串联起来？
- [ ] Catch up with the LaTeX learning
 @EthanDeng
#Readme-edits final version#

**Comment by EthanDeng** [comment]
你前面两张图挂了，应该是路径不对：

![](https://raw.githubusercontent.com/yuewumay/hello-world/master/Quotes1.png)

图的完整路径是：[https://raw.githubusercontent.com/yuewumay/hello-world/master/Quotes1.png](https://raw.githubusercontent.com/yuewumay/hello-world/master/Quotes1.png)

**Comment by EthanDeng** [comment]
紧随其后的话，直接用 
```md
> Coffee. The finest organic suspension ever devised... I beat the Borg with it.  -Captain Janeway
```
就行了，效果如下：

> Coffee. The finest organic suspension ever devised... I beat the Borg with it.  -Captain Janeway

**Comment by EthanDeng** [comment]
第二个问题，编辑器和 git 的绑定操作取决于编辑器，vs code，atom，sublime 都可以，不建议用 vim，目前来说，与 Git/GitHub 结合的最好的编辑器是 atom，因为是 Atom 是 GitHub 自家的。

![QQ截图20191218094724](https://user-images.githubusercontent.com/8111364/71049123-79b83c80-217c-11ea-9366-801b5b8495e1.png)
